id: IECBADDDD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:32:19+00:00'
last_modified: '2022-06-07T12:13:55.531245+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16213
  title: ལེགས་བཤད་འོད་དཀར་འཕྲེང་བ། ༼༡༥༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E184:
      image_group_id: I1KG16246
      title: Volume 1 of legs bshad 'od dkar 'phreng ba/ (15)
      total_pages: 320
      order: 1
      base_file: E184.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
